Django/DAI/DAI/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
 url(r'^restaurantes/', include('restaurantes.urls')),
 url(r'^admin/', include(admin.site.urls)),
 url(r'^accounts/', include('registration.backends.simple.urls')),
]

Django/DAI/restaurantes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^test/$', views.test, name='test'),
  url(r'^cargarrestaurantes/$', views.cargarrestaurantes),
  url(r'^addRestaurantes/$', views.addRestaurantes, name="addRestaurantes"),
  url(r'^eliminar/$', views.eliminar, name="eliminar"),
   url(r'^actualiza/$', views.actualiza, name="actualiza"),

]

Django/DAI/restaurantes/models.py
from __future__ import unicode_literals

from django.db import models
import json
# Create your models here.
from django.conf import settings
TEST = settings.CLIENT.test
RESTAURANTES = settings.CLIENT.test.restaurants

class Restaurantes():
    #def add(self):

    def muestraRestaurantes(self):
        restaurant=RESTAURANTES.find({},{'name':1,'cuisine':1,'borough':1,'_id':0,'restaurant_id':1})
        data={'data':[]}
        for i in restaurant:
            data['data'].append(i)
        return json.dumps(data)
    def add(self,data):
        name=data['nombre']
        borough=data['ciudad']
        restaurant_id=RESTAURANTES.find({},{'_id':0,'restaurant_id':1}).sort('restaurant_id',-1)
        restaurant_id=str(int(restaurant_id[0]['restaurant_id']) +1)
        RESTAURANTES.insert({'name':name,'cuisine':'','borough':borough,'restaurant_id':restaurant_id})
        return RESTAURANTES.find_one({'restaurant_id':str(restaurant_id)},{'_id':0})
    def eliminar(self,id):
        RESTAURANTES.remove({'restaurant_id':id})
    def modificar(self,data):
        restaurant_id=data['id_restaurante']
        name=data['nombre']
        borough=data['ciudad']
        cuisine=''
        RESTAURANTES.update_one({'restaurant_id': restaurant_id},{'$set':{'name':name,'cuisine':cuisine,'borough':borough}})
        return RESTAURANTES.find_one({'restaurant_id': restaurant_id},{'name':1,'cuisine':1,'borough':1,'_id':0,'restaurant_id':1})

Django/DAI/restaurantes/forms.py
from django import forms
from django.core import validators
from restaurantes.models import Restaurantes
import requests
class formAdd(forms.Form):
	nombre = forms.CharField(max_length=65,widget=forms.TextInput({'class': 'form-control', "placeholder": "Introduzca nombre del restaurante"}),required=True)
	ciudad = forms.CharField(max_length=65,widget=forms.TextInput({'class': 'form-control', "placeholder": "Introduzca nombre de la ciudad"}),required=True)
	codigo_postal = forms.IntegerField(widget=forms.NumberInput({ 'class': 'form-control',"placeholder": "Introduzca el codigo postal"}),required=True)
	id_restaurante = forms.CharField(widget=forms.HiddenInput(),required=False)
	def clean_codigo_postal(self):
		r= requests.get('https://maps.googleapis.com/maps/api/geocode/json?address='+self.cleaned_data.get('ciudad', '')+'+'+str(self.cleaned_data.get('codigo_postal', ''))+'&key=AIzaSyCJ3cz5yCNHDgQUUS_cteeyRffpSUIbjTQ')
		h= r.json()
		if (h['results'][0]['address_components'][0]['types'][0]!="postal_code"):

		    raise forms.ValidationError("El codigo postal no pertenece a "+self.cleaned_data.get('ciudad', '')+".")

		return self.cleaned_data.get('codigo_postal', '')
	def save(self):
		resta=Restaurantes()
		return resta.add(self.cleaned_data)
	def update(self):
		resta=Restaurantes()
		return resta.modificar(self.cleaned_data)

Django/DAI/restaurantes/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from restaurantes.models import Restaurantes
import json
from django.http import JsonResponse
from restaurantes.forms import formAdd
# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    form = formAdd()
    return render(request,'restaurantes.html', {'form':form})

def test(request):
    return render(request,'test.html', {})

@login_required
def cargarrestaurantes(request):
    resta=Restaurantes()
    return HttpResponse(resta.muestraRestaurantes())

def addRestaurantes(request):

    if request.method == 'GET':
        return HttpResponse("El metodo utilizado debe ser POST")

    # A POST request: Handle Form Upload
    form = formAdd(request.POST) # Bind data from request.POST into a restaurantes_form

    # If data is valid, proceeds to create a new post and redirect the user
    if form.is_valid():
        #content = form.cleaned_data['content']
        #created_at = form.cleaned_data['created_at']
        #post = m.Post.objects.create(content=content,created_at=created_at)

        return JsonResponse({'mensaje':form.save()})
    else:
        return JsonResponse(form.errors, status=500)

    return JsonResponse({'ok':"AS"})
def eliminar(request):
    if request.method == 'POST':
        return HttpResponse("El metodo utilizado debe ser GET")

    resta=Restaurantes()
    id=request.GET['id']
    assert(id)
    resta.eliminar(id)
    return JsonResponse({'mensaje':"Eliminado con exito"}, status=200)
def actualiza (request):

    if request.method == 'GET':
        return HttpResponse("El metodo utilizado debe ser POST")

    # A POST request: Handle Form Upload
    form = formAdd(request.POST) # Bind data from request.POST into a restaurantes_form

    # If data is valid, proceeds to create a new post and redirect the user
    if form.is_valid():
        #content = form.cleaned_data['content']
        #created_at = form.cleaned_data['created_at']
        #post = m.Post.objects.create(content=content,created_at=created_at)

        return JsonResponse({'mensaje':form.update()})
    else:
        return JsonResponse(form.errors, status=500)

Django/DAI/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}User test{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
</head>

<body>

    <div id="header">
    {% block header %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'index' %}" class="navbar-brand">Restaurantes</a>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    {% if user.is_authenticated %}
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>{{ user.username }}</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu navbar-login">
                        <li>
                            <div class="">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center icon-size">
                                            <span class="glyphicon glyphicon-user"></span>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong>{{ user.username }}</strong></p>
                                        <p class="text-left small">{{ user.email}}</p>

                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider navbar-login-session-bg"></li>
                         <li><a href="{% url 'auth_password_change' %}">Cambiar contraseña <span class="glyphicon glyphicon-cog pull-right"></span></a></li>
            <li class="divider"></li>
            <li><a href="{% url 'auth_logout' %}">Sign Out <span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                    </ul>
                    {% else %}
                    <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
                 {% endif %}
                </li>

            </ul>
        </div>
    </div>
</div>
    <a href="{% url 'index' %}">{% trans "Home" %}</a> |

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }}
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> |
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <div id="content" class="container">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>

</body>

</html>

Django/DAI/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Index page
{% endblock %}

Django/DAI/templates/restaurantes.html
{% extends "base.html" %}
{% block title %}
Restaurantes
{% endblock %}

{% block content %}

 <table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
   <thead>
     <tr>
       <th>restaurant_id</th>
       <th>name</th>
        <th>cuisine</th>
        <th>borough</th>

      </tr>
 </thead>
 <tfoot>

     <td colspan="4">
      <center> <div class="btn-group btn-group-sm text-center">
         <button type="button" class="btn btn-success" id="add" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-plus" ></span> </button>
         <button type="button" id="modi" class="btn btn-info" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-pencil" ></span> </button>
         <button type="button" id="remove" class="btn btn-warning"  ><span class="glyphicon glyphicon-trash"></span></button>

       </div></center>
     </td>



 </tfoot>

</table>
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
 <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
 <script type="text/javascript">
   $(document).ready(function(){
     var restaurante="";
     var btn=0;
     $("#aForm").submit(function(e) {
         e.preventDefault(); // avoid to execute the actual submit of the form.
         if(btn==0)
           insertar()
         else
           actualizar()

       });

     function insertar(){
       $.ajax({
         type: "POST",
         url: "/restaurantes/addRestaurantes/",
         data: $("#aForm").serialize(), // serializes the form's elements.
         dataType: "json",
         headers: {'X-CSRFToken': '{{ csrf_token }}'},
         success: function(data)
         {
           data=data.mensaje

           var table = $('#example').DataTable();
           table.row.add( {
             "restaurant_id":       data.restaurant_id,
             "name":   data.name,
             "cuisine": '',
             "borough": data.borough
           } ).draw()
           $('#myModal').modal('toggle');


        },error: function(data)
        {
         alertas(data.responseJSON)
       }
       });

     }
     function alertas(data){
       $('#alert').html("");
       $("#alert").append('<div class="alert alert-warning"><strong>Warning!</strong> '+JSON.stringify(data)+'</div>')

     }
     function actualizar(){
           $.ajax({
             type: "POST",
             url: "/restaurantes/actualiza/",
             data: $("#aForm").serialize(), // serializes the form's elements.
            dataType: "json",
             success: function(data)
             {
               data=data.mensaje
               $(restaurante[0]).html(data.restaurant_id)
               $(restaurante[1]).html(data.name)
               $(restaurante[3]).html(data.borough)

               $('#myModal').modal('toggle');
             },error:function(data){
              alertas(data.responseJSON)
             }

           });
     }


          $('#example').DataTable({
              "ajax": "/restaurantes/cargarrestaurantes",
              "columns":[

                {"data":"restaurant_id"},
                {"data":"name"},
                 {"data":"cuisine"},
                {"data":"borough"}
              ],
              "language": {
                 "lengthMenu": "Mostrando _MENU_ restaurantes por página",
                 "zeroRecords": "No hay ningun restaurante, lo siento",
                 "info": "Esta es la página _PAGE_ de _PAGES_",
                 "search":         "Buscar:"
               }

          });

          $('#example').on('click','tbody tr',function(){
            restaurante=$(this).find('td');
            $('#example').find('.success').removeClass('success');
            $(this).addClass('success');

          });
          $('#remove').on('click',function(){
            var id=$(restaurante[0]).html();
             $.get("/restaurantes/eliminar/", { 'id':id },function(data,status){

                 var table = $('#example').DataTable();
                 table.row($('#example').find('.success')).remove().draw();
                 restaurante="";

             });

          });
          $('#modi').on('click',function(e){
            btn=1
            if(restaurante!=""){
              $('#titulo').html("Modificar restaurante");
              $('#id_id_restaurante')[0].value=$(restaurante[0]).html();
              $('#id_nombre')[0].value=$(restaurante[1]).html();
              $('#id_ciudad')[0].value=$(restaurante[3]).html();
              $('#btn-signup').html("Modificar");
              $('#alert').html("");
            }else{
                $('#myModal').modal('toggle');
            }


          });
          $('#add').on('click',function(){
            btn=0
            $('#titulo').html("Añadir restaurante nuevo");
            $('#id_nombre')[0].value="";
            $('#id_id_restaurante')[0].value="";
            $('#id_ciudad')[0].value="";
            $('#id_codigo_postal')[0].value="";
            $('#alert').html("");
            $('#btn-signup').html("Añadir");


          });
        });

 </script>
 <!-- Modal -->
   <div class="modal fade" id="myModal" role="dialog">
     <div class="modal-dialog">

       <!-- Modal content-->
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal">&times;</button>
           <h4 id="titulo" class="modal-title">Añadir nuevo restaurante</h4>
         </div>
         <div id="modal" class="modal-body">
           <form  id="aForm"  class="form-horizontal" role="form">
             {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group" id="alert"></div>
            <!-- <input id="id_restaurante" for="id_restaurante" type="hidden" class="form-control" name="id_restaurante">
             <div class="form-group">
                 <label for="nombre" class="col-md-3 control-label">Nombre</label>
                 <div class="col-md-9">
                     <input id="name" type="text" class="form-control" name="nombre" placeholder="Nombre">
                 </div>
             </div>
             <div class="form-group">
                 <label for="ciudad" class="col-md-3 control-label">Ciudad</label>
                 <div class="col-md-9">
                     <input type="text" id="cuisine" class="form-control" name="ciudad" >
                 </div>
             </div>
             <div class="form-group">
                 <label for="direccion" class="col-md-3 control-label">Cocina</label>
                 <div class="col-md-9">
                     <input type="text" id="address" class="form-control" name="direccion" >
                 </div>
             </div>-->

             <div class="form-group">
                 <!-- Button -->
                 <div class="col-md-offset-3 col-md-9">
                     <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i>Añadir</button>
                 </div>
             </div>
           </form>
         </div>
       </div>

     </div>
   </div>

 </div>
{% endblock %}